### ISSUE TITLE
`recompile` in `iex` warning

### ISSUE THREAD

**Issue by am-kantox** [am-kantox/finitomata#54]
```elixir
warning: `Events` process has been attempted to start twice
  (finitomata 0.14.1) lib/mix/tasks/compile/finitomata.ex:20: Mix.Tasks.Compile.Finitomata.run/1
  (mix 1.14.4) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
  (mix 1.14.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.14.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
  (mix 1.14.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
  (mix 1.14.4) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1
```

**Comment by am-kantox** [comment]
Done long ago.
